#!/bin/sh
#!/bin/bash
#!/usr/bin/bash
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/bash
###############################################
# Name : Anlominus ~ RedTeam
# Description : RedTeam ~ Get your target and Hack It.
# Date : 2022 May
Anlominus="Anlominus"
# Last UPDATE : 2022 May 30
# Aouther: Anlominus ~> RhytMix ~> RedTeam
# Skils: Best Copywriter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: To All World Creators free Scripts & Tools
# Location: Made With LOVE IN ISRAEL !
# Source: https://github.com/Anlominus/RedTeam
###############################################
clear
# CODE Functions
# checking for system package manager
if [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
elif [ `command -v brew` ]; then
  pac="brew"
  system="mac"
   sudo=""
elif [ `command -v apt` ]; then
  pac="apt"
  system="linux"
elif [ `command -v apt-get` ]; then
  pac="apt-get"
  system="linux"
elif [ `command -v apk` ]; then
  pac="apk"
  system="linux"
elif [ `command -v yum` ]; then
  pac="yum"
  system="fedora"
fi

RunColors(){
##############################################################################
# COLORS AND BACKGROUNDS
##############################################################################
Color_Off='\033[0m' # Text Reset

# Regular Colors
Black='\033[0;30m'  # Black
Red='\033[0;31m'    # Red
Green='\033[0;32m'  # Green
Yellow='\033[0;33m' # Yellow
Blue='\033[0;34m'   # Blue
Purple='\033[0;35m' # Purple
Cyan='\033[0;36m'   # Cyan
White='\033[0;97m'  # White

# Additional colors
LGrey='\033[0;37m'   # Ligth Gray
DGrey='\033[0;90m'   # Dark Gray
LRed='\033[0;91m'    # Ligth Red
LGreen='\033[0;92m'  # Ligth Green
LYellow='\033[0;93m' # Ligth Yellow
LBlue='\033[0;94m'   # Ligth Blue
LPurple='\033[0;95m' # Light Purple
LCyan='\033[0;96m'   # Ligth Cyan


# Bold
BBlack='\033[1;30m'  # Black
BRed='\033[1;31m'    # Red
BGreen='\033[1;32m'  # Green
BYellow='\033[1;33m' # Yellow
BBlue='\033[1;34m'   # Blue
BPurple='\033[1;35m' # Purple
BCyan='\033[1;36m'   # Cyan
BWhite='\033[1;37m'  # White

# Underline
UBlack='\033[4;30m'  # Black
URed='\033[4;31m'    # Red
UGreen='\033[4;32m'  # Green
UYellow='\033[4;33m' # Yellow
UBlue='\033[4;34m'   # Blue
UPurple='\033[4;35m' # Purple
UCyan='\033[4;36m'   # Cyan
UWhite='\033[4;37m'  # White

# Background
On_Black='\033[40m'  # Black
On_Red='\033[41m'    # Red
On_Green='\033[42m'  # Green
On_Yellow='\033[43m' # Yellow
On_Blue='\033[44m'   # Blue
On_Purple='\033[45m' # Purple
On_Cyan='\033[46m'   # Cyan
On_White='\033[47m'  # White
}
RunColors

A="${BYellow}Anlominus"
echo "
${BGreen}                ..::::::::..                      ${BRed}                      .::^^^^^^::..
${BGreen}            .::::::::::::::::::.                  ${BRed}                  .:^^^^^^^^^^^^^^^^:.
${BGreen}          .::::::::::::::::::::::.                ${BRed}                .^^^^^^^^^^^^^^^^^^^^^^:
${BGreen}        .::::::::::::::::::::::::::               ${BRed}               ^^^^^~?7~^^^^^^^^^7?!^^^^^.
${BGreen}       .:::::::::::::::::::^~!!^::::              ${BRed}              ^^^^^^JBBGJ~^^^^^7PB#5^^^^^^.
${BGreen}       ::::::::::::::::::^~7??7^:::::             ${BRed}             ^^^^^^^^!5B#GJ~~?PBBP7^^^^^^^^
${BGreen}      .::::::::::::::::^!7??!^:::::::             ${BRed}            .^^^^^^^^^^!YGBGGBB57^^^^^^^^^^.
${BGreen}      .:::::^!!~:::::^!???!^:::::::::             ${BRed}            .^^^^^^^^^^^~5BBBBP!^^^^^^^^^^^:
${BGreen}      .^::::^7??7~^^!???!^:::::::::::^:::::::.    ${BRed}    .:::::::^^^^^^^^^^!YGBGYJGBB5!^^^^^^^^^.
${BGreen}       :::::::^!??7??7~^::::::::::::?@@@@@@@@@&P: ${BRed} :P&@@@@@@@@@?^^^^^^!5B#GY~^^~?GBBP7^^^^^^^
${BGreen}        ::::::::^!77~^:::::::::::::7&@@@@@@@@@@@@!${BRed}!@@@@@@@@@@@@&7^^^^^?GGJ~^^^^^^^?PGY^^^^^:
${BGreen}        .^::::::::::::::::::::::::J&@@@@@@@@@@@@@@${BRed}@@@@@@@@@@@@@@&Y^^^^^^^^^^^^^^^^^^~^^^^^~.
${BGreen}      .7??!^:::::::::::::::::::^?B&&&&&&&&&&@@@@@@${BRed}@@@@@@&&&&&&&&&&B?~^^^^^^^^^^^^^^^^^^^~7??7.
${BGreen}      ~?????5P7~:::::::::::^~?G&@@@@@@@@@@@@@@@@@@${BRed}@@@@@@@@@@@@@@@@@@&GJ!^^^^^^^^^^^^~?GP?????~
${BGreen}      ~?????B@@&#BY:::::^5G#&@@@@@@@@@@@@@@@@@@@@@${BRed}@@@@@@@@@@@@@@@@@@@@@&#B5~^^^^^5B&@@@B?????~
${BGreen}      ~?????B@@@@@#:::::^&&&&&&&&&&&&&&&&&&&@@@@@@${BRed}@@@@@@&&&&&&&&&&&&&&&&&&&~^^^^^#@@@@@B?????~
${BGreen}      ~?????B@@@@@#:::::^&@@@@@@@@@@@@@@@@@@@@@@@@${BRed}@@@@@@@@@@@@@@@@@@@@@@@@&~^^^^^#@@@@@B?????~
${BGreen}      ~?????B@@@@@#:::::^&@@&&&&&&&&&&&&&&&@@@@@@@${BRed}@@@@@@@&&&&&&&&&&&&&&&@@&~^^^^^#@@@@@B?????~
${BGreen}      ~?????B@@@@@B:::::^B##&&&&&&&&&&&&&&&&@@@@@@${BRed}@@@@@@&&&&&&&&&&&&&&&&###~^^^^^B@@@@@B?????~
${BGreen}      ~?????B@&~^~^::::::^^^?@@@@@@@@@@@@@@@@@@@@@${BRed}@@@@@@@@@@@@@@@@@@@@@?~~~^^^^^^~!~!&@B?????~
${BGreen}      ~?????B@@P~::::::::::!G&&&&&&&&&&&&&&@@@@@@@${BRed}@@@@@@@&&&&&&&&&&&&&&G7^^^^^^^^^^!P@@B?????~
${BGreen}      ~?????B@@@@G!::::::7G&&&&&&&&&&&&&&&&&@@@@@@${BRed}@@@@@@&&&&&&&&&&&&&&&&&G?^^^^^^7G@@@@B?????~
${BGreen}      ~?????B@@@@@@B7^^J#@@@@@@@@@@@@@@@@@@@@@@@@@${BRed}@@@@@@@@@@@@@@@@@@@@@@@@@#J~~?B@@@@@@B?????~
${BGreen}      ~?????7Y&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@${BRed}@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&Y7?????~
${BGreen}      ~??????77JPBBBBBBBBBBBBBBBBBBBBBBBBBBB#&&@@@${BRed}@@@&&#BBBBBBBBBBBBBBBBBBBBBBBBBBBPJ77??????~
${BGreen}      ~?????????7777777777777777777777777777777Y#@${BRed}@#Y7777777777777777777777777777777?????????~
${BGreen}      :?????????????????????????????????????????7G${BRed}G7?????????????????????????????????????????:
${BGreen}       .:^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^~777777777${BRed}777777777~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^:.
${BGreen}                                         :~~~~~~~~${BRed}~~~~~~~~:

"
